### ISSUE TITLE
the banner image and text should be vertically centered

### ISSUE THREAD

**Issue by Shruti3004** [winterofcode/winterofcode2020#3] opened 2021-02-25 23:45 UTC
![Screenshot from 2021-02-26 05-13-01](https://user-images.githubusercontent.com/56133783/109234359-8eb54480-77f1-11eb-87c1-19c9fb640b67.png)

**Comment by xprilion** [comment] 2021-02-26 01:52
Hi @Shruti3004, any particular reason why you feel it should be vertically centered?

**Comment by Shruti3004** [comment] 2021-02-26 06:41
Hey @xprilion, from UI prespective it will give a better look to the site.

**Comment by xprilion** [comment] 2021-02-26 06:44
I think the issue appears on devices with larger screens ( I was able to replicate it by zooming out a lot)

@vishwajeetraj11 can you please take a look? I believe the issue is well found (kudos to @Shruti3004 🎉  ) and we should plan around solving it.

**Comment by vishwajeetraj11** [comment] 2021-02-27 06:28
Sure, will fix that.

**Comment by xprilion** [comment] 2021-02-27 06:29
@Shruti3004 would you like to send in a fix for this?

**Comment by vishwajeetraj11** [comment] 2021-03-01 17:13
I fixed it. most probably. 🙂

**Comment by xprilion** [comment] 2021-03-01 17:23
@vishwajeetraj11 can you please link the fix PR with this issue? (Use the Fixes notation on the PR) 

Also, I am still able to replicate the issue. Can you please check?

**Closed as completed** 2021-03-01 18:31 UTC
